### ISSUE TITLE
package in npm doesn't appear to have been babel-ified

### ISSUE THREAD

**Issue by jboerjes** [Cimpress/cimpress-fulfillment-location#8]
using npm install to get the latest package from npm results in ES6 code in my ./node_modules/fulfillment-location-client source code. which is not usable in the browser/react components we're building.

**Comment by jboerjes** [comment]
There appear to be a couple of things that need doing:
1) the dist directory either needs to be copied to a new directory ("lib"? ) 
or 
2) remove the src directory as this carries the raw .js code
then
3) add "main": "dist/index.js" or ("lib/index.js" if that's where we move the babel'd code to) to package.json

Right now, the package gets installed, but when node tries to find the module using require, it is pulling src/*.js

**Comment by rnowosielski** [comment]
I assume the ticket is fixed. If not, don't hesitate to reopen.
